const path = require("path");

/**
 * Production Entry Point for cPanel (CloudLinux Passenger).
 * Point your cPanel Node.js Application "Application startup file" to this server.js.
 *
 * This file serves the 'standalone' build generated by 'next build'.
 * It ensures static files and public assets are correctly mapped.
 */

// Port is provided by cPanel/Passenger automatically
const port = process.env.PORT || 3000;

// Load the standalone server generated by Next.js
const serverPath = path.join(__dirname, ".next", "standalone", "server.js");

process.on("uncaughtException", (err) => {
  console.error("❌ CRITICAL: Uncaught Exception:", err);
});

try {
  console.log(`🚀 Starting UKP2SA Production Server on port ${port}...`);

  // The standalone server is NOT Express, it's pure Node.js http.
  // This fixes [H2] and [M2] about Express crash and identification.
  require(serverPath);
} catch {
  const http = require("http");
  const server = http.createServer((req, res) => {
    res.writeHead(500, { "Content-Type": "application/json" });
    res.end(
      JSON.stringify({
        error: "Internal Server Error",
        message:
          "Server failed to start. Check if standalone build is uploaded correctly.",
      }),
    );
  });
  server.listen(port);
}
